# Find LibIDN library
#
# This module defines
# LibIDN_FOUND - whether the LibIDN was found
# LibIDN_LIBRARIES - LibIDN libraries
# LibIDN_INCLUDE_DIR - the include path of the LibIDN library

FIND_PATH (LibIDN_INCLUDE_DIR stringprep.h)
FIND_LIBRARY (LibIDN_LIBRARY idn)

INCLUDE (FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS (LibIDN DEFAULT_MSG LibIDN_LIBRARY LibIDN_INCLUDE_DIR)
SET (LibIDN_FOUND LIBIDN_FOUND)

IF (LibIDN_FOUND)
	SET (LibIDN_LIBRARIES ${LibIDN_LIBRARY})
	SET (LibIDN_INCLUDE_DIRS ${LibIDN_INCLUDE_DIR})
ELSE (LibIDN_FOUND)
	SET (LibIDN_LIBRARIES)
	SET (LibIDN_INCLUDE_DIRS)
ENDIF (LibIDN_FOUND)
