Document: swarm
Title: Debian swarm Manual
Author: <insert document author here>
Abstract: This manual describes what swarm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/swarm/swarm.sgml.gz

Format: postscript
Files: /usr/share/doc/swarm/swarm.ps.gz

Format: text
Files: /usr/share/doc/swarm/swarm.text.gz

Format: HTML
Index: /usr/share/doc/swarm/html/index.html
Files: /usr/share/doc/swarm/html/*.html
